### ISSUE TITLE
Access to dataset

### ISSUE THREAD

**Issue by brahmakulkarni** [carpentries-incubator/SDC-BIDS-fMRI#20]
Could you provide me access to some part of the entire dataset that you have? I wish to perform some experiments and want to be able to generate correlation maps between various parcels/voxels. Having access to a few subjects would be splendid!

**Comment by jerdra** [comment]
Hi @brahmakulkarni the dataset is available on an open source platform: https://openneuro.org/!

Check out the https://github.com/carpentries-incubator/SDC-BIDS-fMRI/blob/gh-pages/code/setup_workshop for the key lines that will enable you to download the dataset.

If you only wanted the minimal amt of data in order to run the notebooks (we use this in our CI testing), then https://github.com/carpentries-incubator/SDC-BIDS-fMRI/blob/gh-pages/code/setup_test should suffice!

Lmk if you have any questions/run into any issues!

**Comment by brahmakulkarni** [comment]
Hi @jerdra. Thank you for all the links! For my purposes, I would just like to work with a small amount of data. Hence, I think, the last link you shared is what I need to use. However, I would like to know if you could provide some insight into how to generate the brain mask files and all the other extra files that you have used, in addition to the vanilla fMRI data.

**Comment by jerdra** [comment]
Hey, all the files that we use for the course are included in the test download link, this includes the mask file, and the spatially transformed versions of the vanilla data.

If you mean to ask how these files were generated. They are outputs from a popular fMRI pre-processing pipeline called fMRIPrep (https://fmriprep.org/en/stable/). The particular dataset that we use in the workshop provides fMRIPrep pipeline outputs (the mask file, MNI transformed files, confound files, etc) - albeit a much older version than what is currently available

Hope that answers your question!

**Comment by brahmakulkarni** [comment]
@jerdra Thank you so much for the assistance! As this is resolved, I am closing this issue now.
